spring:
  application:
    name: customer-service

management:
  endpoints:
    web:
      exposure:
        include: '*'

opentracing:
  jaeger:
    log-spans: true
    http-sender:
      url: http://jaeger-collector-jaeger.apps.c3smonkey.ch/api/traces

---
spring:
  profiles: local
opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces